version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: some-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Book_Store
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  app:
    image: my-go-app:latest
    build: .
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
